source 'https://rubygems.org'
ruby '3.2.2'

gem 'rails', '~> 7.1.0'
gem 'sqlite3', '~> 1.7'
gem 'puma', '>= 6.0'
gem 'rack-cors'
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails', '~> 6.1'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.3'
end

group :test do
  gem 'shoulda-matchers', '~> 6.0'
end
